# Generated by Django 4.2.7 on 2024-09-12 13:56

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("data", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Asteroid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Asteroid-default", max_length=30)),
                ("data", models.JSONField(null=True)),
                (
                    "size",
                    models.JSONField(default=core.models.get_default_asteroid_size),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CashShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Faction-default", max_length=30)),
                ("data", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, max_length=2500)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("ATTACK", "attack"),
                            ("DEFENSE", "defense"),
                            ("ZONE_CHANGE", "zone change"),
                            ("DEATH", "death"),
                            ("KILL", "kill"),
                            ("CRAFT_END", "craft end"),
                            ("RESEARCH_END", "research end"),
                            ("LEVEL_UP", "level up"),
                        ],
                        default=("ATTACK", "attack"),
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Light Cruiser", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("tier", models.SmallIntegerField(default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NONE", "none"),
                            ("WEAPONRY", "weaponry"),
                            ("DEFENSE", "defense"),
                            ("MOVEMENT", "movement"),
                            ("GATHERING", "gathering"),
                            ("PROBE", "probe"),
                            ("REPAIR", "repair"),
                            ("ELECTRONIC_WARFARE", "electronic warfare"),
                            ("RESEARCH", "research"),
                            ("CRAFT", "craft"),
                            ("HOLD", "hold"),
                            ("COLONIZATION", "colonization"),
                        ],
                        default="NONE",
                        max_length=30,
                    ),
                ),
                ("effect", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NpcTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("difficulty", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("module_id_list", models.JSONField(null=True)),
                ("current_hp", models.SmallIntegerField(default=100)),
                ("max_hp", models.SmallIntegerField(default=100)),
                ("current_movement", models.PositiveSmallIntegerField(default=10)),
                ("max_movement", models.PositiveSmallIntegerField(default=10)),
                ("current_missile_defense", models.SmallIntegerField(default=0)),
                ("current_thermal_defense", models.SmallIntegerField(default=0)),
                ("current_ballistic_defense", models.SmallIntegerField(default=0)),
                ("current_cargo_size", models.SmallIntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FULL", "pleine forme"),
                            ("WOUNDED", "blesse"),
                            ("DEAD", "mort"),
                        ],
                        default=("FULL", "pleine forme"),
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Planet-default", max_length=30)),
                ("data", models.JSONField(null=True)),
                ("size", models.JSONField(default=core.models.get_default_planet_size)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_npc", models.BooleanField(default=False)),
                ("name", models.CharField(default="Faction", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                (
                    "image",
                    models.CharField(
                        blank=True, default="img.png", max_length=250, null=True
                    ),
                ),
                ("faction_xp", models.PositiveIntegerField(default=0)),
                ("current_ap", models.PositiveIntegerField(default=10)),
                ("max_ap", models.PositiveBigIntegerField(default=10)),
                ("coordinates", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archetype",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_archetype",
                        to="core.archetype",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        default=core.models.Faction.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="player_faction",
                        to="core.faction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_current_ship", models.BooleanField(default=True)),
                ("is_reversed", models.BooleanField(default=False)),
                ("module_id_list", models.JSONField(null=True)),
                ("current_hp", models.SmallIntegerField(default=100)),
                ("max_hp", models.SmallIntegerField(default=100)),
                ("current_movement", models.PositiveSmallIntegerField(default=10)),
                ("max_movement", models.PositiveSmallIntegerField(default=10)),
                ("current_missile_defense", models.SmallIntegerField(default=0)),
                ("current_thermal_defense", models.SmallIntegerField(default=0)),
                ("current_ballistic_defense", models.SmallIntegerField(default=0)),
                ("current_cargo_size", models.SmallIntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FULL", "pleine forme"),
                            ("WOUNDED", "blesse"),
                            ("DEAD", "mort"),
                        ],
                        default=("FULL", "pleine forme"),
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Resource-default", max_length=30)),
                ("data", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Sector", max_length=30)),
                ("image", models.CharField(default="img.png", max_length=250)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("is_faction_level_starter", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faction",
                    models.ForeignKey(
                        default=core.models.Faction.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="faction_sector",
                        to="core.faction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("attack_countdown", models.PositiveSmallIntegerField(default=3)),
                ("chance_to_intervene", models.PositiveSmallIntegerField(default=100)),
                ("ship_quantity", models.PositiveSmallIntegerField(default=3)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShipCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Light Cruiser", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("ship_size", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Skill1", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STEERING", "steering"),
                            ("OFFENSIVE", "offensive"),
                            ("DEFENSIVE", "defensive"),
                            ("UTILITY", "utility"),
                            ("INDUSTRY", "industry"),
                        ],
                        default=("STEERING", "steering"),
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Station-default", max_length=30)),
                ("data", models.JSONField(null=True)),
                (
                    "size",
                    models.JSONField(default=core.models.get_default_station_size),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resource",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_sector",
                        to="core.sector",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.station"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_level_range", models.PositiveIntegerField(default=0)),
                ("max_level_range", models.PositiveIntegerField(default=1)),
                ("effect", models.JSONField()),
                (
                    "expertise",
                    models.CharField(
                        choices=[
                            ("ROOKIE", "Rookie"),
                            ("QUALIFIED", "Qualified"),
                            ("PROFESSIONAL", "Professional"),
                            ("EXPERT", "Expert"),
                            ("GREAT_EXPERT", "Great expert"),
                            ("MASTER", "Master"),
                            ("GRAND_MASTER", "Grand master"),
                        ],
                        default=("ROOKIE", "Rookie"),
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.skill"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("image", models.CharField(default="img.png", max_length=250)),
                ("module_slot_available", models.PositiveIntegerField(default=4)),
                ("default_hp", models.PositiveSmallIntegerField(default=100)),
                ("default_movement", models.PositiveSmallIntegerField(default=10)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ship_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.shipcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sector",
            name="security",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="security_sector",
                to="core.security",
            ),
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Recipe1", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("image", models.CharField(default="img.png", max_length=250)),
                ("time_to_complete", models.PositiveIntegerField(default=86400)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Recipe1", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("value_needed", models.FloatField(default=1.0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=0)),
                ("progress", models.FloatField(default=1.0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerShipResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.resource",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.playership",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playership",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.ship"
            ),
        ),
        migrations.CreateModel(
            name="PlayerResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resource",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.research"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerPrivateMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=2500)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="core.player",
                    ),
                ),
                (
                    "player_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.log"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_sector",
                to="core.sector",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="PlanetResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("data", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resource",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planet_sector",
                        to="core.sector",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.planet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NpcTemplateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "npc_template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.npctemplate",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NpcTemplateResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "npc_template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.npctemplate",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="npctemplate",
            name="ship",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.ship"
            ),
        ),
        migrations.CreateModel(
            name="Npc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_npc", models.BooleanField(default=False)),
                ("name", models.CharField(default="npc", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                (
                    "image",
                    models.CharField(
                        blank=True, default="img.png", max_length=250, null=True
                    ),
                ),
                ("faction_xp", models.PositiveIntegerField(default=0)),
                ("current_ap", models.PositiveIntegerField(default=10)),
                ("max_ap", models.PositiveBigIntegerField(default=10)),
                ("coordinates", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faction",
                    models.ForeignKey(
                        default=core.models.Faction.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="npc_faction",
                        to="core.faction",
                    ),
                ),
                (
                    "npc_teplate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.npctemplate",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="npc_sector",
                        to="core.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactionResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resource",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faction_sector",
                        to="core.sector",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.faction"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactionRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Rank1", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("responsibility_level", models.PositiveSmallIntegerField(default=0)),
                ("faction_xp_required", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.faction"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactionLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.faction"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsteroidResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("data", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resource",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asteroid_sector",
                        to="core.sector",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.asteroid"
                    ),
                ),
            ],
        ),
    ]
