# Generated by Django 4.2.7 on 2024-04-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipcategory",
            name="ship_size",
            field=models.JSONField(null=True),
        ),
    ]
