# Generated by Django 4.2.7 on 2024-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.CharField(default="img.png", max_length=250),
        ),
        migrations.AlterField(
            model_name="research",
            name="image",
            field=models.CharField(default="img.png", max_length=250),
        ),
        migrations.AlterField(
            model_name="sector",
            name="image",
            field=models.CharField(default="img.png", max_length=250),
        ),
        migrations.AlterField(
            model_name="ship",
            name="image",
            field=models.CharField(default="img.png", max_length=250),
        ),
    ]
