# Generated by Django 4.2.7 on 2023-12-22 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSkillEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=0)),
                ("progress", models.FloatField(default=1.0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_level_range", models.PositiveIntegerField(default=0)),
                ("max_level_range", models.PositiveIntegerField(default=1)),
                ("effect", models.JSONField()),
                (
                    "expertise",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "beginner"),
                            ("STANDARD", "standard"),
                            ("PROFESSIONAL", "professional"),
                            ("EXPERT", "expert"),
                            ("GREAT_EXPERT", "great expert"),
                            ("MASTER", "master"),
                            ("GRAND_MASTER", "grand master"),
                        ],
                        default=("BEGINNER", "beginner"),
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("ATTACK", "attack"),
                    ("DEFENSE", "defense"),
                    ("ZONE_CHANGE", "zone_change"),
                    ("DEATH", "death"),
                    ("KILL", "kill"),
                    ("CRAFT_END", "craft_end"),
                    ("RESEARCH_END", "research_end"),
                    ("LEVEL_UP", "level_up"),
                ],
                default=("ATTACK", "attack"),
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("STEERING", "steering"),
                    ("OFFENSIVE", "offensive"),
                    ("DEFENSIVE", "defensive"),
                    ("UTILITY", "utility"),
                    ("INDUSTRY", "industry"),
                ],
                default=("STEERING", "steering"),
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="PlayerSkill",
        ),
        migrations.AddField(
            model_name="skilleffect",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.skill"
            ),
        ),
        migrations.AddField(
            model_name="playerskilleffect",
            name="skill_effect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.skilleffect"
            ),
        ),
    ]
