# Generated by Django 4.2.7 on 2025-02-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorWarp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Sector", max_length=30)),
                ("data", models.JSONField(null=True)),
                ("size", models.JSONField(null=True)),
                (
                    "warp_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warp_destination",
                        to="core.sector",
                    ),
                ),
                (
                    "warp_home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warp_home",
                        to="core.sector",
                    ),
                ),
            ],
        ),
    ]
