# Generated by Django 4.2.7 on 2024-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playership",
            name="max_hp",
        ),
        migrations.RemoveField(
            model_name="shipcategory",
            name="max_speed",
        ),
        migrations.AddField(
            model_name="playership",
            name="current_movement",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="ship",
            name="default_hp",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="ship",
            name="default_movement",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="playership",
            name="current_hp",
            field=models.SmallIntegerField(default=100),
        ),
    ]
