# Generated by Django 4.2.7 on 2024-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_playerskilleffect_skilleffect_alter_log_log_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="user_default", unique=True),
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="expertise",
            field=models.CharField(
                choices=[
                    ("ROOKIE", "Rookie"),
                    ("QUALIFIED", "Qualified"),
                    ("PROFESSIONAL", "Professional"),
                    ("EXPERT", "Expert"),
                    ("GREAT_EXPERT", "Great expert"),
                    ("MASTER", "Master"),
                    ("GRAND_MASTER", "Grand master"),
                ],
                default=("ROOKIE", "Rookie"),
            ),
        ),
    ]
