# Generated by Django 4.2.7 on 2025-05-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_loggedinuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="archetype",
            name="ship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_ship",
                to="core.ship",
            ),
        ),
    ]
