# Generated by Django 4.2.7 on 2024-04-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_shipcategory_ship_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="ship_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.shipcategory",
            ),
        ),
    ]
