# Generated by Django 4.2.7 on 2024-06-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_playership_max_hp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playership",
            name="max_hp",
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="playership",
            name="max_movement",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
