# Generated by Django 4.2.7 on 2024-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_player_image_alter_research_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="blank@email.com", max_length=254),
        ),
    ]
