# Generated by Django 4.2.7 on 2025-02-03 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sectorwarp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Warp", max_length=30)),
                ("size", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="sectorwarp",
            name="size",
        ),
        migrations.AddField(
            model_name="sectorwarp",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="sectorwarp",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sectorwarp",
            name="name",
            field=models.CharField(default="SectorWarp", max_length=30),
        ),
        migrations.AddField(
            model_name="sectorwarp",
            name="warp",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.warp"
            ),
        ),
    ]
