# Generated by Django 4.2.7 on 2024-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_npctemplateresource_can_be_randomized_npcresource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npc",
            name="npc_teplate",
        ),
        migrations.AlterField(
            model_name="module",
            name="type",
            field=models.CharField(
                choices=[
                    ("NONE", "none"),
                    ("WEAPONRY", "weaponry"),
                    ("DEFENSE_BALLISTIC", "defense_ballistic"),
                    ("DEFENSE_THERMAL", "defense_thermal"),
                    ("DEFENSE_MISSILE", "defense_missile"),
                    ("HULL", "hull"),
                    ("MOVEMENT", "movement"),
                    ("GATHERING", "gathering"),
                    ("PROBE", "probe"),
                    ("REPAIR", "repair"),
                    ("ELECTRONIC_WARFARE", "electronic warfare"),
                    ("RESEARCH", "research"),
                    ("CRAFT", "craft"),
                    ("HOLD", "hold"),
                    ("COLONIZATION", "colonization"),
                ],
                default="NONE",
                max_length=30,
            ),
        ),
    ]
