# Generated by Django 4.2.7 on 2025-10-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_privatemessage_privatemessagerecipients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privatemessagerecipients",
            old_name="recipients",
            new_name="recipient",
        ),
    ]
