# Generated by Django 4.2.7 on 2025-02-03 14:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_warp_remove_sectorwarp_size_sectorwarp_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warp",
            name="data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="warp",
            name="size",
            field=models.JSONField(default=core.models.get_default_warzone_size),
        ),
    ]
