# Generated by Django 4.2.7 on 2025-10-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_recipients_privatemessagerecipients_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessagerecipients",
            name="is_author",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="privatemessagerecipients",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient",
                to="core.player",
            ),
        ),
    ]
