# Generated by Django 4.2.7 on 2024-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_npc_npc_teplate_alter_module_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="npctemplate",
            old_name="current_ballistic_defense",
            new_name="ballistic_defense",
        ),
        migrations.RenameField(
            model_name="npctemplate",
            old_name="current_cargo_size",
            new_name="hold_capacity",
        ),
        migrations.RenameField(
            model_name="npctemplate",
            old_name="current_hp",
            new_name="hp",
        ),
        migrations.RenameField(
            model_name="npctemplate",
            old_name="current_missile_defense",
            new_name="missile_defense",
        ),
        migrations.RenameField(
            model_name="npctemplate",
            old_name="current_movement",
            new_name="movement",
        ),
        migrations.RenameField(
            model_name="npctemplate",
            old_name="current_thermal_defense",
            new_name="thermal_defense",
        ),
        migrations.RemoveField(
            model_name="npctemplate",
            name="max_hp",
        ),
        migrations.RemoveField(
            model_name="npctemplate",
            name="max_movement",
        ),
        migrations.AlterField(
            model_name="npctemplate",
            name="difficulty",
            field=models.SmallIntegerField(default=1),
        ),
    ]
