# Generated by Django 4.2.7 on 2024-05-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ship_ship_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetresource",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
