# Generated by Django 4.2.7 on 2024-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_archetype_playerarchetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="archetype",
            name="description",
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
