# Generated by Django 4.2.7 on 2024-06-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_playership_max_hp_playership_max_movement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playershipmodule",
            name="data",
        ),
    ]
