# Generated by Django 4.2.7 on 2025-05-23 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_archetype_ship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerskill",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="ArchetypeModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.archetype"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.module"
                    ),
                ),
            ],
        ),
    ]
