# Generated by Django 4.2.7 on 2025-10-28 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_privatemessagerecipients_is_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="deleted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="privatemessagerecipients",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="privatemessagerecipients",
            name="deleted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="privatemessagerecipients",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
