# Generated by Django 4.2.7 on 2025-05-23 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_playerskill_progress_archetypemodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="playershipresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="playershipresource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PlayerShipModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.module"
                    ),
                ),
                (
                    "player_ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.playership",
                    ),
                ),
            ],
        ),
    ]
