# Generated by Django 4.2.7 on 2024-03-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.CharField(
                blank=True, default="img.png", max_length=250, null=True
            ),
        ),
    ]
