# Generated by Django 4.2.7 on 2024-03-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_archetype_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerarchetype",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_archetype",
                to="core.player",
            ),
        ),
    ]
