# Generated by Django 4.2.7 on 2025-02-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_warp_data_alter_warp_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="warp",
            new_name="resource_id",
        ),
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="warp_destination",
            new_name="sector_destination_id",
        ),
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="warp_home",
            new_name="source_id",
        ),
    ]
