# Generated by Django 4.2.7 on 2024-06-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_planetresource_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="module_effect",
        ),
        migrations.AddField(
            model_name="module",
            name="effect",
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name="ModuleEffect",
        ),
    ]
