# Generated by Django 4.2.7 on 2024-02-15 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_map_sector_map"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planet",
            old_name="coordinates",
            new_name="data",
        ),
        migrations.RemoveField(
            model_name="planet",
            name="description",
        ),
    ]
