# Generated by Django 4.2.7 on 2024-06-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_playershipmodule_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="playership",
            name="is_current_ship",
            field=models.BooleanField(default=True),
        ),
    ]
