# Generated by Django 4.2.7 on 2025-05-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_playershipresource_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playership",
            name="module_id_list",
        ),
    ]
