# Generated by Django 4.2.7 on 2025-10-28 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_privatemessage_created_at_privatemessage_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatemessage",
            name="deleted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="delete date"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessagerecipients",
            name="deleted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="delete date"
            ),
        ),
    ]
