# Generated by Django 4.2.7 on 2024-06-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_module_module_effect_module_effect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="type",
            field=models.CharField(
                choices=[
                    ("NONE", "none"),
                    ("WEAPONRY", "weaponry"),
                    ("DEFENSE", "defense"),
                    ("MOVEMENT", "movement"),
                    ("GATHERING", "gathering"),
                    ("PROBE", "probe"),
                    ("REPAIR", "repair"),
                    ("ELECTRONIC_WARFARE", "electronic warfare"),
                    ("RESEARCH", "research"),
                    ("HOLD", "hold"),
                    ("COLONIZATION", "colonization"),
                ],
                default=("NONE", "none"),
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("ATTACK", "attack"),
                    ("DEFENSE", "defense"),
                    ("ZONE_CHANGE", "zone change"),
                    ("DEATH", "death"),
                    ("KILL", "kill"),
                    ("CRAFT_END", "craft_end"),
                    ("RESEARCH_END", "research end"),
                    ("LEVEL_UP", "level up"),
                ],
                default=("ATTACK", "attack"),
                max_length=20,
            ),
        ),
    ]
