# Generated by Django 4.2.7 on 2024-02-15 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_coordinates_planet_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planet",
            name="image",
        ),
    ]
