# Generated by Django 4.2.7 on 2024-03-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_playerarchetype_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="archetype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_archetype",
                to="core.archetype",
            ),
        ),
        migrations.DeleteModel(
            name="PlayerArchetype",
        ),
    ]
