# Generated by Django 4.2.7 on 2024-06-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_playership_is_current_ship"),
    ]

    operations = [
        migrations.AddField(
            model_name="playershipmodule",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_player",
                to="core.player",
            ),
            preserve_default=False,
        ),
    ]
