# Generated by Django 4.2.7 on 2025-02-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_warp_sectorwarp_resource_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="resource_id",
            new_name="resource",
        ),
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="sector_destination_id",
            new_name="sector_destination",
        ),
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="source_id",
            new_name="source",
        ),
    ]
