# Generated by Django 4.2.7 on 2025-05-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_playership_module_id_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipcategory",
            name="ship_category_hp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shipcategory",
            name="ship_category_movement",
            field=models.IntegerField(default=0),
        ),
    ]
