# Generated by Django 4.2.7 on 2024-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_module_type_alter_log_log_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("ATTACK", "attack"),
                    ("DEFENSE", "defense"),
                    ("ZONE_CHANGE", "zone change"),
                    ("DEATH", "death"),
                    ("KILL", "kill"),
                    ("CRAFT_END", "craft end"),
                    ("RESEARCH_END", "research end"),
                    ("LEVEL_UP", "level up"),
                ],
                default=("ATTACK", "attack"),
                max_length=20,
            ),
        ),
    ]
