# Generated by Django 4.2.7 on 2025-02-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_resource_id_sectorwarp_resource_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="resource",
            new_name="warp",
        ),
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="sector_destination",
            new_name="warp_destination",
        ),
        migrations.RenameField(
            model_name="sectorwarp",
            old_name="source",
            new_name="warp_home",
        ),
    ]
