# Generated by Django 4.2.7 on 2024-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_playershipmodule_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="playership",
            name="module_id_list",
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name="PlayerShipModule",
        ),
    ]
