# Generated by Django 4.2.7 on 2024-02-19 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_asteroid_coordinates_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="map",
        ),
        migrations.DeleteModel(
            name="Map",
        ),
    ]
