# Generated by Django 4.2.7 on 2025-05-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_shipcategory_ship_category_hp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="default_ballistic_defense",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ship",
            name="default_missile_defense",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ship",
            name="default_thermal_defense",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ship",
            name="module_slot_available",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="ShipModuleLimitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defense_module_limitation",
                    models.PositiveSmallIntegerField(default=3),
                ),
                (
                    "weaponry_module_limitation",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("hold_module_limitation", models.PositiveSmallIntegerField(default=1)),
                (
                    "movement_module_limitation",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("hull_module_limitation", models.PositiveSmallIntegerField(default=1)),
                (
                    "repair_module_limitation",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "gathering_module_limitation",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "craft_module_limitation",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "research_module_limitation",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "electronic_warfare_module_limitation",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "colonization_warfare_module_limitation",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ship_module_limitation",
                        to="core.ship",
                    ),
                ),
            ],
        ),
    ]
