# Generated by Django 4.2.7 on 2025-02-11 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_resource_sectorwarp_warp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorWarpZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WarpZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="SectorWarp", max_length=50)),
                ("data", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sector"
                    ),
                ),
                (
                    "warp",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.warp",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SectorWarp",
        ),
        migrations.AddField(
            model_name="sectorwarpzone",
            name="warp_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warp_destination",
                to="core.warpzone",
            ),
        ),
        migrations.AddField(
            model_name="sectorwarpzone",
            name="warp_home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warp_home",
                to="core.warpzone",
            ),
        ),
    ]
