# Generated by Django 4.2.7 on 2024-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_playership_module_id_list_delete_playershipmodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="playership",
            name="current_ballistic_defense",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playership",
            name="current_cargo_size",
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="playership",
            name="current_laser_defense",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playership",
            name="current_missile_defense",
            field=models.SmallIntegerField(default=0),
        ),
    ]
