# Generated by Django 4.2.7 on 2025-02-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_sectorwarpzone_warpzone_delete_sectorwarp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warpzone",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warp_sector",
                to="core.sector",
            ),
        ),
    ]
