# Generated by Django 4.2.7 on 2025-10-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_privatemessagerecipients_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatemessage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="delete date"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessagerecipients",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="delete date"
            ),
        ),
    ]
