# Generated by Django 4.2.7 on 2024-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_sector_map_delete_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="asteroid",
            name="name",
            field=models.CharField(default="Asteroid-default", max_length=30),
        ),
        migrations.AddField(
            model_name="faction",
            name="name",
            field=models.CharField(default="Faction-default", max_length=30),
        ),
        migrations.AddField(
            model_name="planet",
            name="name",
            field=models.CharField(default="Planet-default", max_length=30),
        ),
        migrations.AddField(
            model_name="resource",
            name="name",
            field=models.CharField(default="Resource-default", max_length=30),
        ),
        migrations.AddField(
            model_name="station",
            name="name",
            field=models.CharField(default="Station-default", max_length=30),
        ),
    ]
