# Generated by Django 4.2.7 on 2024-06-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_module_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="type",
            field=models.CharField(
                choices=[
                    ("NONE", "none"),
                    ("WEAPONRY", "weaponry"),
                    ("DEFENSE", "defense"),
                    ("MOVEMENT", "movement"),
                    ("GATHERING", "gathering"),
                    ("PROBE", "probe"),
                    ("REPAIR", "repair"),
                    ("ELECTRONIC_WARFARE", "electronic warfare"),
                    ("RESEARCH", "research"),
                    ("CRAFT", "craft"),
                    ("HOLD", "hold"),
                    ("COLONIZATION", "colonization"),
                ],
                default="NONE",
                max_length=30,
            ),
        ),
    ]
