# Generated by Django 4.2.7 on 2024-06-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_playership_current_ballistic_defense_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playership",
            old_name="current_laser_defense",
            new_name="current_thermal_defense",
        ),
    ]
