# Generated by Django 4.2.7 on 2025-05-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_ship_default_ballistic_defense_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipmodulelimitation",
            old_name="colonization_warfare_module_limitation",
            new_name="colonization_module_limitation",
        ),
    ]
