# Generated by Django 4.2.7 on 2024-06-25 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0009_rename_current_laser_defense_playership_current_thermal_defense",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=0)),
                ("progress", models.FloatField(default=1.0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlayerSkillEffect",
        ),
    ]
