# Generated by Django 4.2.7 on 2024-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_module_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="tier",
            field=models.SmallIntegerField(default=1),
        ),
    ]
