# Generated by Django 4.2.7 on 2025-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_privatemessage_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
