# Generated by Django 4.2.7 on 2025-02-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_warpzone_sector"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warpzone",
            old_name="warp",
            new_name="source",
        ),
    ]
