# Generated by Django 4.2.7 on 2025-05-26 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0009_rename_colonization_warfare_module_limitation_shipmodulelimitation_colonization_module_limitation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmodulelimitation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="shipmodulelimitation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
