# Generated by Django 4.2.7 on 2024-06-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_playerskill_delete_playerskilleffect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="time_to_play",
        ),
        migrations.AddField(
            model_name="player",
            name="current_ap",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="player",
            name="max_ap",
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
