# Generated by Django 4.2.7 on 2024-02-21 13:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_asteroidresource_sector_factionresource_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asteroid",
            name="size",
            field=models.JSONField(default=core.models.get_default_asteroid_size),
        ),
        migrations.AddField(
            model_name="planet",
            name="size",
            field=models.JSONField(default=core.models.get_default_planet_size),
        ),
        migrations.AddField(
            model_name="station",
            name="size",
            field=models.JSONField(default=core.models.get_default_station_size),
        ),
    ]
