# Generated by Django 4.2.7 on 2025-05-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_skillexperience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playershipmodule",
            name="player_ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_ship_module",
                to="core.playership",
            ),
        ),
    ]
