# Generated by Django 4.2.7 on 2024-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_player_time_to_play_player_current_ap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playership",
            name="is_reversed",
            field=models.BooleanField(default=False),
        ),
    ]
