# Generated by Django 4.2.7 on 2024-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_asteroid_size_planet_size_station_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="security_level",
            field=models.CharField(
                choices=[
                    ("NULL", "null"),
                    ("LOW", "low security"),
                    ("MEDIUM", "basic security"),
                    ("HIGH", "high security"),
                ],
                default=("NULL", "null"),
                max_length=20,
            ),
        ),
    ]
