# Generated by Django 4.2.7 on 2024-09-09 10:46

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_playership_is_reversed"),
    ]

    operations = [
        migrations.CreateModel(
            name="NpcTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("difficulty", models.SmallIntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("module_id_list", models.JSONField(null=True)),
                ("current_hp", models.SmallIntegerField(default=100)),
                ("max_hp", models.SmallIntegerField(default=100)),
                ("current_movement", models.PositiveSmallIntegerField(default=10)),
                ("max_movement", models.PositiveSmallIntegerField(default=10)),
                ("current_missile_defense", models.SmallIntegerField(default=0)),
                ("current_thermal_defense", models.SmallIntegerField(default=0)),
                ("current_ballistic_defense", models.SmallIntegerField(default=0)),
                ("current_cargo_size", models.SmallIntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FULL", "pleine forme"),
                            ("WOUNDED", "blesse"),
                            ("DEAD", "mort"),
                        ],
                        default=("FULL", "pleine forme"),
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NpcResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "npc_template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.npctemplate",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Npc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_npc", models.BooleanField(default=False)),
                ("name", models.CharField(default="npc", max_length=30)),
                ("description", models.TextField(blank=True, max_length=2500)),
                (
                    "image",
                    models.CharField(
                        blank=True, default="img.png", max_length=250, null=True
                    ),
                ),
                ("faction_xp", models.PositiveIntegerField(default=0)),
                ("current_ap", models.PositiveIntegerField(default=10)),
                ("max_ap", models.PositiveBigIntegerField(default=10)),
                ("coordinates", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation date"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faction",
                    models.ForeignKey(
                        default=core.models.Faction.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="npc_faction",
                        to="core.faction",
                    ),
                ),
                (
                    "npc_teplate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.npctemplate",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="npc_sector",
                        to="core.sector",
                    ),
                ),
            ],
        ),
    ]
