# Generated by Django 4.2.7 on 2024-02-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_sector_security_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("attack_countdown", models.PositiveSmallIntegerField(default=3)),
                ("chance_to_intervene", models.FloatField(default=1.0)),
                ("ship_quantity", models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.RemoveField(
            model_name="sector",
            name="security_level",
        ),
        migrations.AddField(
            model_name="sector",
            name="security",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.security",
            ),
        ),
    ]
