# Generated by Django 4.2.7 on 2025-06-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_playershipmodule_player_ship"),
    ]

    operations = [
        migrations.AddField(
            model_name="playership",
            name="max_ballistic_defense",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playership",
            name="max_missile_defense",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playership",
            name="max_thermal_defense",
            field=models.SmallIntegerField(default=0),
        ),
    ]
