# Generated by Django 4.2.7 on 2025-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_group_message_sectormessage_playergroup_groupmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_time_warpzone",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
