# Generated by Django 4.2.7 on 2025-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_playership_max_ballistic_defense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="npctemplate",
            name="displayed_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
