# Generated by Django 4.2.7 on 2024-02-28 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_security_remove_sector_security_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AddField(
            model_name="security",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
