# Generated by Django 4.2.7 on 2025-11-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_player_last_time_warpzone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectormessage",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
