# Generated by Django 4.2.7 on 2025-11-17 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_sectormessage_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factionmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_time_warpzone",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sectormessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
