# Generated by Django 4.2.7 on 2025-07-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_npctemplate_displayed_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warpzone",
            name="name",
        ),
    ]
