# Generated by Django 4.2.7 on 2024-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_security_created_at_security_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="chance_to_intervene",
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
