# Generated by Django 4.2.7 on 2025-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_warpzone_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="playership",
            name="view_range",
            field=models.SmallIntegerField(default=6),
        ),
    ]
