# Generated by Django 4.2.7 on 2025-11-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_factionmessage_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factionmessage",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sectormessage",
            name="updated_at",
        ),
    ]
