# Generated by Django 4.2.7 on 2024-02-29 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_security_chance_to_intervene"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factionresource",
            old_name="faction",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="planetresource",
            old_name="planet",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="playerresource",
            old_name="player",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="playershipresource",
            old_name="player_ship",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="stationresource",
            old_name="station",
            new_name="source",
        ),
    ]
