# Generated by Django 4.2.7 on 2025-11-17 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_factionmessage_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archetype",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 197660, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="archetypemodule",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 202772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="asteroid",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 194163, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="asteroidresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 207418, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 195161, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="factionleader",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 205360, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="factionrank",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 206417, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="factionresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 206417, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 208418, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 199771, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 202772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="npc",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 201772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="npcresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 201772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="npctemplate",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 200770, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="npctemplateresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 200770, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="npctemplateskill",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 200770, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="planetresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 206417, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 198194, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playergroup",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 208418, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playerlog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 202772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playerrecipe",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 203778, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playerresearch",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 204303, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playerresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 202772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playership",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 204835, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playershipmodule",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 205360, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playershipresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 204835, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="playerskill",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 203778, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 207418, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessagerecipients",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 208418, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 199771, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="research",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 199771, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 194163, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 195161, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="sectorwarpzone",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 196242, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="security",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 195161, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 197122, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="shipcategory",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 196242, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="shipmodulelimitation",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 197660, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 198731, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 199256, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="skillexperience",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 199256, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 194163, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="stationresource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 207418, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="warp",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 195161, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
        migrations.AlterField(
            model_name="warpzone",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 17, 9, 36, 17, 196242, tzinfo=datetime.timezone.utc
                ),
                verbose_name="creation date",
            ),
        ),
    ]
