# Generated by Django 4.2.7 on 2024-02-29 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_rename_faction_factionresource_source_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asteroidresource",
            old_name="asteroid",
            new_name="source",
        ),
    ]
