# Generated by Django 4.2.7 on 2025-10-23 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0017_alter_sector_image_privatemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatemessage",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
