# Generated by Django 4.2.7 on 2024-02-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_rename_asteroid_asteroidresource_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="asteroidresource",
            name="data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="planetresource",
            name="data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="stationresource",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
