# Generated by Django 4.2.7 on 2025-11-17 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_archetype_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archetype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="archetypemodule",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="asteroid",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="asteroidresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="factionleader",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="factionrank",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="factionresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="npc",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="npcresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="npctemplate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="npctemplateresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="npctemplateskill",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="planetresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playergroup",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playerlog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playerrecipe",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playerresearch",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playerresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playership",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playershipmodule",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playershipresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="playerskill",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessagerecipients",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="research",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="sectorwarpzone",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="security",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="shipcategory",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="shipmodulelimitation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="skillexperience",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="stationresource",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="warp",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="warpzone",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation date"
            ),
        ),
    ]
