# Generated by Django 4.2.7 on 2025-11-17 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_archetype_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name="factionmessage",
            name="faction",
        ),
        migrations.RemoveField(
            model_name="factionmessage",
            name="message",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="message",
        ),
        migrations.RemoveField(
            model_name="sectormessage",
            name="message",
        ),
        migrations.RemoveField(
            model_name="sectormessage",
            name="sector",
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[
                    ("SECTOR", "sector"),
                    ("FACTION", "faction"),
                    ("GROUP", "group"),
                ],
                default="SECTOR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="faction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_messages",
                to="core.faction",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_messages",
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sector_messages",
                to="core.sector",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "sector", "-created_at"],
                name="core_messag_channel_3826ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "faction", "-created_at"],
                name="core_messag_channel_9d7672_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "group", "-created_at"],
                name="core_messag_channel_768781_idx",
            ),
        ),
        migrations.DeleteModel(
            name="FactionMessage",
        ),
        migrations.DeleteModel(
            name="GroupMessage",
        ),
        migrations.DeleteModel(
            name="SectorMessage",
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_by",
                to="core.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_read_statuses",
                to="core.player",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["player", "is_read"], name="core_messag_player__340d19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["message", "is_read"], name="core_messag_message_14a054_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereadstatus",
            unique_together={("player", "message")},
        ),
    ]
