# Generated by Django 4.2.7 on 2024-02-29 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_asteroidresource_data_planetresource_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asteroidresource",
            name="max_quantity",
        ),
        migrations.RemoveField(
            model_name="planetresource",
            name="max_quantity",
        ),
        migrations.RemoveField(
            model_name="stationresource",
            name="quantity",
        ),
    ]
