# Generated by Django 4.2.7 on 2025-10-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_privatemessage_recipients_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlayerPrivateMessage",
        ),
    ]
