# Generated by Django 4.2.7 on 2025-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_messagereadstatus_remove_factionmessage_faction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Basse"),
                    ("NORMAL", "Normale"),
                    ("HIGH", "Haute"),
                    ("URGENT", "Urgente"),
                ],
                default="LOW",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["priority", "-timestamp"], name="core_privat_priorit_72130a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(
                fields=["-timestamp"], name="core_privat_timesta_7014d7_idx"
            ),
        ),
    ]
