# Generated by Django 4.2.7 on 2024-02-29 13:36

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_asteroidresource_max_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.resource"
            ),
        ),
        migrations.AlterField(
            model_name="asteroidresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.sector"
            ),
        ),
        migrations.AlterField(
            model_name="factionresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.resource"
            ),
        ),
        migrations.AlterField(
            model_name="factionresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.sector"
            ),
        ),
        migrations.AlterField(
            model_name="planetresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.resource"
            ),
        ),
        migrations.AlterField(
            model_name="planetresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.sector"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="faction",
            field=models.ForeignKey(
                default=core.models.Sector.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.faction",
            ),
        ),
        migrations.AlterField(
            model_name="stationresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.resource"
            ),
        ),
        migrations.AlterField(
            model_name="stationresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.sector"
            ),
        ),
    ]
