# Generated by Django 4.2.7 on 2024-03-04 09:13

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_asteroidresource_resource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asteroid_resource_sector",
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="factionresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_resource_sector",
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="planetresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planet_resource_sector",
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="faction",
            field=models.ForeignKey(
                default=core.models.Sector.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="player_faction",
                to="core.faction",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="sector",
            field=models.ForeignKey(
                default=core.models.Sector.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="player_sector",
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="stationresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_resource_sector",
                to="core.sector",
            ),
        ),
    ]
