# Generated by Django 4.2.7 on 2025-12-19 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_privatemessage_priority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanIntel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated", models.BooleanField(default=False)),
                (
                    "invalidation_reason",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("target_type", models.CharField(max_length=3)),
                ("target_id", models.IntegerField()),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_author",
                        to="core.player",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_sector",
                        to="core.sector",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CombatEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated", models.BooleanField(default=False)),
                (
                    "invalidation_reason",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("stat", models.CharField(max_length=32)),
                ("value", models.IntegerField(default=0)),
                (
                    "target_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_effect_author",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
