# Generated by Django 4.2.7 on 2025-12-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_scanintel_combateffect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combateffect",
            name="target_player",
        ),
        migrations.AlterModelOptions(
            name="scanintel",
            options={
                "verbose_name": "Scan Intel",
                "verbose_name_plural": "Scan Intels",
            },
        ),
        migrations.RenameField(
            model_name="scanintel",
            old_name="created_at",
            new_name="scanned_at",
        ),
        migrations.RemoveField(
            model_name="scanintel",
            name="sector",
        ),
        migrations.AddField(
            model_name="scanintel",
            name="sector_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="scanintel",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="scanintel",
            name="scanner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_intels",
                to="core.player",
            ),
        ),
        migrations.AlterField(
            model_name="scanintel",
            name="target_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="scanintel",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("pc", "Player"),
                    ("npc", "NPC"),
                    ("foreground", "Foreground"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="scanintel",
            index=models.Index(
                fields=["scanner", "target_type", "target_id"],
                name="core_scanin_scanner_8a3093_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scanintel",
            index=models.Index(
                fields=["expires_at"], name="core_scanin_expires_edac86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanintel",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="core_scanin_target__2e0ab3_idx",
            ),
        ),
        migrations.DeleteModel(
            name="CombatEffect",
        ),
    ]
