# Generated by Django 4.2.7 on 2024-03-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_asteroidresource_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asteroid_sector",
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="factionresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_sector",
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="planetresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planet_sector",
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="stationresource",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_sector",
                to="core.sector",
            ),
        ),
    ]
