# Generated by Django 4.2.7 on 2024-03-05 08:47

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_asteroidresource_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="faction",
            field=models.ForeignKey(
                default=core.models.Faction.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sector_faction",
                to="core.faction",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="security",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sector_security",
                to="core.security",
            ),
        ),
    ]
