# Generated by Django 4.2.7 on 2025-12-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_combateffect_target_player_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScanIntel",
        ),
    ]
