# Generated by Django 4.2.7 on 2025-12-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_delete_scanintel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("pc", "Player"),
                            ("npc", "NPC"),
                            ("foreground", "Foreground"),
                        ],
                        max_length=12,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans_emitted",
                        to="core.player",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sector"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scanner", "target_type", "target_id"],
                        name="core_scanef_scanner_39d20e_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_scanef_expires_9bb33c_idx"
                    ),
                ],
            },
        ),
    ]
