# Generated by Django 4.2.7 on 2024-03-05 08:48

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_sector_faction_alter_sector_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="faction",
            field=models.ForeignKey(
                default=core.models.Faction.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_sector",
                to="core.faction",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="security",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_sector",
                to="core.security",
            ),
        ),
    ]
