# Generated by Django 4.2.7 on 2025-12-19 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_scaneffect"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanIntel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanner_player_id", models.IntegerField(db_index=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("pc", "pc"), ("npc", "npc")], max_length=8
                    ),
                ),
                ("target_id", models.IntegerField(db_index=True)),
                ("sector_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScanIntelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_reciever",
                        to="core.group",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_to_group",
                        to="core.scanintel",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="scanintel",
            index=models.Index(
                fields=["scanner_player_id", "sector_id"],
                name="core_scanin_scanner_d8e362_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scanintel",
            index=models.Index(
                fields=["target_type", "target_id", "sector_id"],
                name="core_scanin_target__3c3495_idx",
            ),
        ),
    ]
