# Generated by Django 4.2.7 on 2025-12-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_scanintel_scanintelgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanintel",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="scanintelgroup",
            unique_together={("scan", "group")},
        ),
        migrations.AddIndex(
            model_name="scanintelgroup",
            index=models.Index(fields=["group"], name="core_scanin_group_i_391e91_idx"),
        ),
    ]
