# Generated by Django 4.2.7 on 2025-12-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_scanintel_invalidated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanintelgroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_reciever",
                to="core.playergroup",
            ),
        ),
    ]
