# Generated by Django 4.2.7 on 2026-01-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_scanintelgroup_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="max_ballistic_defense",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="npc",
            name="max_hp",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="npc",
            name="max_missile_defense",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="npc",
            name="max_movement",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="npc",
            name="max_thermal_defense",
            field=models.SmallIntegerField(default=0),
        ),
    ]
