# Generated by Django 4.2.7 on 2026-01-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_npc_max_ballistic_defense_npc_max_hp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npc",
            name="max_ballistic_defense",
        ),
        migrations.RemoveField(
            model_name="npc",
            name="max_missile_defense",
        ),
        migrations.RemoveField(
            model_name="npc",
            name="max_movement",
        ),
        migrations.RemoveField(
            model_name="npc",
            name="max_thermal_defense",
        ),
    ]
