# Generated by Django 4.2.7 on 2026-01-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_npc_max_ballistic_defense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerlog",
            name="role",
            field=models.CharField(
                choices=[
                    ("TRANSMITTER", "transmitter"),
                    ("RECEIVER", "receiver"),
                    ("OBSERVER", "observer"),
                ],
                default="TRANSMITTER",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="content",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("ATTACK", "attack"),
                    ("DEFENSE", "defense"),
                    ("ZONE_CHANGE", "zone change"),
                    ("DEATH", "death"),
                    ("KILL", "kill"),
                    ("CRAFT", "craft"),
                    ("RESEARCH", "research"),
                    ("LEVEL_UP", "level up"),
                    ("OTHER", "other"),
                ],
                default=("ATTACK", "attack"),
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="npc",
            name="coordinates",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="coordinates",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="skilleffect",
            name="effect",
            field=models.JSONField(null=True),
        ),
    ]
