# Generated by Django 4.2.27 on 2026-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_playerlog_role_alter_log_content_alter_log_log_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="is_tutorial_zone",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("ATTACK", "attack"),
                    ("DEFENSE", "defense"),
                    ("SCAN", "scan"),
                    ("ZONE_CHANGE", "zone change"),
                    ("DEATH", "death"),
                    ("KILL", "kill"),
                    ("CRAFT", "craft"),
                    ("RESEARCH", "research"),
                    ("LEVEL_UP", "level up"),
                    ("OTHER", "other"),
                ],
                default=("ATTACK", "attack"),
                max_length=20,
            ),
        ),
    ]
