# Generated by Django 4.2.27 on 2026-02-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_sector_is_tutorial_zone_alter_log_log_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npc",
            name="max_hp",
        ),
    ]
