# Generated by Django 4.2.27 on 2026-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_player_status_shipwreck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[("ALIVE", "alive"), ("DEAD", "dead")],
                default=("ALIVE", "alive"),
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipwreck",
            name="origin_type",
            field=models.CharField(
                choices=[("PC", "player"), ("NPC", "npc")],
                default=("PC", "player"),
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shipwreck",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("LOOTED", "looted"),
                    ("SALVAGED", "salvaged"),
                    ("EXPIRED", "expired"),
                ],
                default=("ACTIVE", "active"),
                max_length=20,
            ),
        ),
    ]
