# Generated by Django 4.2.27 on 2026-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_groupinvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playershipmodulereconfiguration',
            new_name='core_player_player__1dc6a2_idx',
            old_name='core_players_player__f9af6e_idx',
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['player', 'is_read', 'message'], name='mrs_player_read_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessagerecipients',
            index=models.Index(fields=['recipient', 'deleted_at', 'is_author', '-created_at'], name='pmr_rec_tab_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessagerecipients',
            index=models.Index(fields=['recipient', 'is_read', 'is_author', 'deleted_at'], name='pmr_rec_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessagerecipients',
            index=models.Index(fields=['message', 'recipient'], name='pmr_msg_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessagerecipients',
            index=models.Index(fields=['message', 'deleted_at'], name='pmr_msg_del_idx'),
        ),
    ]
