name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DEBUG: 1
  REPOS_NAME: recorp
  IMG_TAB: latest

jobs:
  test-and-build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Activate venv and install dep (debug mode)


      if: ${{ env.DEBUG == 1 }}
      run: |
        echo 'Hi, project in DEV mod'
        python -m venv venv
        cd venv/scripts/activate
        .\activate
        cd ..
        cd ..
        echo 'requirements setup...'
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        python .\setup_env.py

    - name: install dep (prod mod)
      if: ${{ env.DEBUG == 0 }}
      run: |
        echo 'Hi, project in PROD mod'
        python -m pip install --upgrade pip
        echo 'requirements setup...'
        pip install -r requirements.txt
        python .\setup_env.py

    - name: Black test
      run: |
        . venv/scripts/activate
        echo 'black testing...'
        black --line-length=99 .

    - name: Linting test
      run: |
        . venv/scripts/activate
        echo 'flake8 testing...'
        flake8

    - name: Other tests
      run: |
        . venv/scripts/activate
        echo 'pytest testing...'
        python manage.py test
